def annual():
    return 1
def semiannual():
    return 2
def every_fourth_month():
    return 3
def quarterly():
    return 4
def bimonthly():
    return 6
def monthly():
    return 12
def daily():
    return 365
